---




- name: start redis
  ansible.builtin.systemd:
    name: redis-server
    state: started
    daemon_reload: yes


- name: restart redis
  ansible.builtin.systemd:
    name: redis-server
    state: restarted
    daemon_reload: yes


