---

- name: Spin up a VPS in Los Angeles
  ngine_io.vultr.vultr_server:
    name: "nft-alerts"
    os: Ubuntu 20.04 x64
    region: Los Angeles
    plan: 2048 MB RAM,55 GB SSD,2.00 TB BW
    ssh_keys:
      - 612fa1f7d1e42
    tag: nft-alerts
    state: present
  register: server_output


- name: Create a 69G volume for UBQ blockchain
  vultr_block_storage:
    name: ubq
    size: 69
    region: Los Angeles
    state: attached
    attached_to_id: "{{ server_output.vultr_server.id | int }}"




- name: Refresh Inventory
  meta: refresh_inventory
